### ISSUE TITLE
email are not converted into ticket as mailbox is case sensitive

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#64]
**Description**  
email are not converted into ticket as mailbox is case sensitive

**How to reproduce**  
as a customer, mail to abc@gmail.com OR Abc@gmail.com, both mails will be received as email id are not sensitive but on UVDesk only a single ticket will be created.

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master [here](https://github.com/uvdesk/mailbox-component/commit/78b0c6a05436440964c79d99df18ad7fc5b2c1d0#diff-a63373476297809e8bc0da0daf31d9fa3789f352ec6c1ebb5b25985828049eaaR307).

locate path in your project:
**vendor/uvdesk/mailbox-component/Services/MailboxService.php**

Open **MailboxService.php** and replace its code from [here](https://github.com/uvdesk/mailbox-component/blob/master/Services/MailboxService.php).

**Comment by PeopleInside** [comment]
Hi @papnoisanjeev , I see this issue and applied the patch.
After no ticket was opened by email.
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/109857934-8038b400-7c5b-11eb-9573-6ad3fc86d653.jpg)

Did you tested the patch?
Hope you don't made updates that broke things.
I restored my backup.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Clear your project cache:

**php bin/console c:c**

**Comment by PeopleInside** [comment]
Have you tested: tried to open ticket by email? In my test did not work... the update broken totally my system as ticket was no more opened by email. I think I cleared cache because I made two updates, one is the fix here and other one I tried to update jQuery but get errors so cache was clean.

I opened a new issue asking you to see how update jQuery that has security fix.
I will not madding changes here, hope when you will release a new version of Uvdesk this update doesn't broken ticket creation by email so I hope the issue I facing testing your fix here was mine and not a bug in the file.

Seems uvdesk open source update are very slow or also you may update here the code that will be no longer matches with code of my installation that is latest one stable released.

Your fix here add one row but if I compare my file with your many different row has been changed... so who know where the issue can be? Maybe in other patch somewhere else you did?

I cannot fully test if you update the code but did not release an updated version of the software.

**Comment by vaishaliwebkul** [comment]
I have verified this issue and working fine,
please see screenshot
https://prnt.sc/10il99t
https://prnt.sc/10ilaur
